// Code generated by goctl. DO NOT EDIT.
package types

type FileUploadRequest struct {
}

type FileUploadResponse struct {
	Identity string `json:"identity"`
}

type FileUploadByChunkRequest struct {
}

type FileUploadByChunkResponse struct {
	Identity string `json:"identity"`
}
