// Code generated by goctl. DO NOT EDIT.
package types

type DetailRequest struct {
	Identity string `json:"identity"`
}

type DetailResponse struct {
	RepositoryIdentity string `json:"repositoryIdentity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int64  `json:"size"`
	Path               string `json:"path"`
}

type ShareBasicCreateRequest struct {
	UserRepositoryIdentity string `json:"userRepositoryIdentity"`
	ExpiredTime            int64  `json:"expiredTime"`
}

type ShareBasicCreateResponse struct {
	Identity string `json:"identity"`
}

type ShareBasicSaveRequest struct {
	RepositoryIdentity string `json:"repositoryIdentity"` //分享的文件identity
	ParentId           int64  `json:"parentId"`           //保存在该parentId目录下
}

type ShareBasicSaveResponse struct {
	Identity string `json:"identity"`
}
