// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"butane-netdisk/service/user_repository/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/repository/save",
				Handler: UserRepositorySaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/file/list",
				Handler: UserFileListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/folder/list",
				Handler: UserFolderListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/file/name/update",
				Handler: UserFileNameUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/folder/create",
				Handler: UserFolderCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/file/delete",
				Handler: UserFileDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/file/move",
				Handler: UserFileMoveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
