// Code generated by goctl. DO NOT EDIT.
package types

type UserRepositorySaveRequest struct {
	ParentId           int64  `json:"parentId"`
	RepositoryIdentity string `json:"repositoryIdentity"`
	Name               string `json:"name"`
}

type UserRepositorySaveResponse struct {
}

type UserFileListRequest struct {
	Identity string `json:"identity"`      //查询的文件夹identity
	Page     int64  `json:"page,optional"` //查询的第几页
	Size     int64  `json:"size,optional"` //每页页数
}

type UserFileListResponse struct {
	List  []*UserFile `json:"list"`
	Count int64       `json:"count"`
}

type UserFile struct {
	Id                 int64  `json:"id"`
	Identity           string `json:"identity"`
	RepositoryIdentity string `json:"repositoryIdentity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Path               string `json:"path"`
	Size               int64  `json:"size"`
}

type UserFolderListRequest struct {
	Identity string `json:"identity"`
}

type UserFolderListResponse struct {
	List []*UserFolder `json:"list"`
}

type UserFolder struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFileNameUpdateRequest struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFileNameUpdateResponse struct {
}

type UserFolderCreateRequest struct {
	ParentId int64  `json:"parentId"`
	Name     string `json:"name"`
}

type UserFolderCreateResponse struct {
	Identity string `json:"identity"`
}

type UserFileDeleteRequest struct {
	Identity string `json:"identity"`
}

type UserFileDeleteResponse struct {
}

type UserFileMoveRequest struct {
	Identity string `json:"identity"`
	ParentId int64  `json:"parentId"`
}

type UserFileMoveResponse struct {
}
