// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: userRepository.proto

package userRepository

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepositoryIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepositoryId int64 `protobuf:"varint,1,opt,name=repositoryId,proto3" json:"repositoryId,omitempty"`
}

func (x *RepositoryIdReq) Reset() {
	*x = RepositoryIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userRepository_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepositoryIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryIdReq) ProtoMessage() {}

func (x *RepositoryIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_userRepository_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryIdReq.ProtoReflect.Descriptor instead.
func (*RepositoryIdReq) Descriptor() ([]byte, []int) {
	return file_userRepository_proto_rawDescGZIP(), []int{0}
}

func (x *RepositoryIdReq) GetRepositoryId() int64 {
	if x != nil {
		return x.RepositoryId
	}
	return 0
}

type UserRepositoryNameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepositoryName string `protobuf:"bytes,1,opt,name=repositoryName,proto3" json:"repositoryName,omitempty"`
}

func (x *UserRepositoryNameReply) Reset() {
	*x = UserRepositoryNameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userRepository_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRepositoryNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRepositoryNameReply) ProtoMessage() {}

func (x *UserRepositoryNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_userRepository_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRepositoryNameReply.ProtoReflect.Descriptor instead.
func (*UserRepositoryNameReply) Descriptor() ([]byte, []int) {
	return file_userRepository_proto_rawDescGZIP(), []int{1}
}

func (x *UserRepositoryNameReply) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

type FindRepositoryIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindRepositoryIdReq) Reset() {
	*x = FindRepositoryIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userRepository_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRepositoryIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRepositoryIdReq) ProtoMessage() {}

func (x *FindRepositoryIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_userRepository_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRepositoryIdReq.ProtoReflect.Descriptor instead.
func (*FindRepositoryIdReq) Descriptor() ([]byte, []int) {
	return file_userRepository_proto_rawDescGZIP(), []int{2}
}

func (x *FindRepositoryIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindRepositoryIdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepositoryId int64 `protobuf:"varint,1,opt,name=repositoryId,proto3" json:"repositoryId,omitempty"`
}

func (x *FindRepositoryIdReply) Reset() {
	*x = FindRepositoryIdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userRepository_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRepositoryIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRepositoryIdReply) ProtoMessage() {}

func (x *FindRepositoryIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_userRepository_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRepositoryIdReply.ProtoReflect.Descriptor instead.
func (*FindRepositoryIdReply) Descriptor() ([]byte, []int) {
	return file_userRepository_proto_rawDescGZIP(), []int{3}
}

func (x *FindRepositoryIdReply) GetRepositoryId() int64 {
	if x != nil {
		return x.RepositoryId
	}
	return 0
}

type CreateByShareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ParentId     int64  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	RepositoryId int64  `protobuf:"varint,3,opt,name=repositoryId,proto3" json:"repositoryId,omitempty"`
	Name         string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateByShareReq) Reset() {
	*x = CreateByShareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userRepository_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateByShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateByShareReq) ProtoMessage() {}

func (x *CreateByShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_userRepository_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateByShareReq.ProtoReflect.Descriptor instead.
func (*CreateByShareReq) Descriptor() ([]byte, []int) {
	return file_userRepository_proto_rawDescGZIP(), []int{4}
}

func (x *CreateByShareReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateByShareReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateByShareReq) GetRepositoryId() int64 {
	if x != nil {
		return x.RepositoryId
	}
	return 0
}

func (x *CreateByShareReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateByShareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateByShareReply) Reset() {
	*x = CreateByShareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userRepository_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateByShareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateByShareReply) ProtoMessage() {}

func (x *CreateByShareReply) ProtoReflect() protoreflect.Message {
	mi := &file_userRepository_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateByShareReply.ProtoReflect.Descriptor instead.
func (*CreateByShareReply) Descriptor() ([]byte, []int) {
	return file_userRepository_proto_rawDescGZIP(), []int{5}
}

func (x *CreateByShareReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_userRepository_proto protoreflect.FileDescriptor

var file_userRepository_proto_rawDesc = []byte{
	0x0a, 0x14, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x35, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x41, 0x0a,
	0x17, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x25, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xbc, 0x02, 0x0a, 0x0e, 0x75,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x6f, 0x0a,
	0x23, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x62,
	0x0a, 0x14, 0x66, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x42, 0x79, 0x49, 0x64, 0x12, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x55, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x12, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userRepository_proto_rawDescOnce sync.Once
	file_userRepository_proto_rawDescData = file_userRepository_proto_rawDesc
)

func file_userRepository_proto_rawDescGZIP() []byte {
	file_userRepository_proto_rawDescOnce.Do(func() {
		file_userRepository_proto_rawDescData = protoimpl.X.CompressGZIP(file_userRepository_proto_rawDescData)
	})
	return file_userRepository_proto_rawDescData
}

var file_userRepository_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_userRepository_proto_goTypes = []interface{}{
	(*RepositoryIdReq)(nil),         // 0: userRepository.RepositoryIdReq
	(*UserRepositoryNameReply)(nil), // 1: userRepository.UserRepositoryNameReply
	(*FindRepositoryIdReq)(nil),     // 2: userRepository.FindRepositoryIdReq
	(*FindRepositoryIdReply)(nil),   // 3: userRepository.FindRepositoryIdReply
	(*CreateByShareReq)(nil),        // 4: userRepository.CreateByShareReq
	(*CreateByShareReply)(nil),      // 5: userRepository.CreateByShareReply
}
var file_userRepository_proto_depIdxs = []int32{
	0, // 0: userRepository.userRepository.getUserRepositoryNameByRepositoryId:input_type -> userRepository.RepositoryIdReq
	2, // 1: userRepository.userRepository.findRepositoryIdById:input_type -> userRepository.FindRepositoryIdReq
	4, // 2: userRepository.userRepository.createByShare:input_type -> userRepository.CreateByShareReq
	1, // 3: userRepository.userRepository.getUserRepositoryNameByRepositoryId:output_type -> userRepository.UserRepositoryNameReply
	3, // 4: userRepository.userRepository.findRepositoryIdById:output_type -> userRepository.FindRepositoryIdReply
	5, // 5: userRepository.userRepository.createByShare:output_type -> userRepository.CreateByShareReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userRepository_proto_init() }
func file_userRepository_proto_init() {
	if File_userRepository_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userRepository_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepositoryIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userRepository_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRepositoryNameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userRepository_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRepositoryIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userRepository_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRepositoryIdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userRepository_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateByShareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userRepository_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateByShareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userRepository_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userRepository_proto_goTypes,
		DependencyIndexes: file_userRepository_proto_depIdxs,
		MessageInfos:      file_userRepository_proto_msgTypes,
	}.Build()
	File_userRepository_proto = out.File
	file_userRepository_proto_rawDesc = nil
	file_userRepository_proto_goTypes = nil
	file_userRepository_proto_depIdxs = nil
}
