// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"butane-netdisk/service/repository/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: FileUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/chunk/upload",
				Handler: FileUploadByChunkHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
