// Code generated by goctl. DO NOT EDIT.
package types

type UserRepositorySaveRequest struct {
	ParentId     int64  `json:"parentId"`
	RepositoryId int64  `json:"repositoryId"`
	Name         string `json:"name"`
}

type UserRepositorySaveResponse struct {
}

type UserFileListRequest struct {
	Id   int64 `json:"id"`            //查询的文件夹id
	Page int64 `json:"page,optional"` //查询的第几页
	Size int64 `json:"size,optional"` //每页页数
}

type UserFileListResponse struct {
	List  []*UserFile `json:"list"`
	Count int64       `json:"count"`
}

type UserFile struct {
	Id           int64  `json:"id"`
	RepositoryId int64  `json:"repositoryId"`
	Name         string `json:"name"`
	Ext          string `json:"ext"`
	Path         string `json:"path"`
	Size         int64  `json:"size"`
}

type UserFolderListRequest struct {
	Id int64 `json:"id"`
}

type UserFolderListResponse struct {
	List []*UserFolder `json:"list"`
}

type UserFolder struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UserFileNameUpdateRequest struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UserFileNameUpdateResponse struct {
}

type UserFolderCreateRequest struct {
	ParentId int64  `json:"parentId"`
	Name     string `json:"name"`
}

type UserFolderCreateResponse struct {
	Id int64 `json:"id"`
}

type UserFileDeleteRequest struct {
	Id int64 `json:"id"`
}

type UserFileDeleteResponse struct {
}

type UserFileMoveRequest struct {
	Id       int64 `json:"id"`
	ParentId int64 `json:"parentId"`
}

type UserFileMoveResponse struct {
}
