// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shareBasicFieldNames          = builder.RawFieldNames(&ShareBasic{})
	shareBasicRows                = strings.Join(shareBasicFieldNames, ",")
	shareBasicRowsExpectAutoSet   = strings.Join(stringx.Remove(shareBasicFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), ",")
	shareBasicRowsWithPlaceHolder = strings.Join(stringx.Remove(shareBasicFieldNames, "`id`", "`create_at`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`"), "=?,") + "=?"

	cacheShareBasicIdPrefix = "cache:shareBasic:id:"
)

type (
	shareBasicModel interface {
		Insert(ctx context.Context, data *ShareBasic) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ShareBasic, error)
		Update(ctx context.Context, data *ShareBasic) error
		Delete(ctx context.Context, id int64) error
	}

	defaultShareBasicModel struct {
		sqlc.CachedConn
		table string
	}

	ShareBasic struct {
		Id                     int64          `db:"id"`
		Identity               sql.NullString `db:"identity"`
		UserIdentity           sql.NullString `db:"user_identity"`
		RepositoryIdentity     sql.NullString `db:"repository_identity"`      // 公共池中的唯一标识
		UserRepositoryIdentity sql.NullString `db:"user_repository_identity"` // 用户池子中的唯一标识
		ExpiredTime            sql.NullInt64  `db:"expired_time"`             // 失效时间，单位秒, 【0-永不失效】
		ClickNum               int64          `db:"click_num"`                // 点击次数
		CreatedAt              sql.NullTime   `db:"created_at"`
		UpdatedAt              sql.NullTime   `db:"updated_at"`
		DeletedAt              sql.NullTime   `db:"deleted_at"`
	}
)

func newShareBasicModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultShareBasicModel {
	return &defaultShareBasicModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`share_basic`",
	}
}

func (m *defaultShareBasicModel) Delete(ctx context.Context, id int64) error {
	shareBasicIdKey := fmt.Sprintf("%s%v", cacheShareBasicIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, shareBasicIdKey)
	return err
}

func (m *defaultShareBasicModel) FindOne(ctx context.Context, id int64) (*ShareBasic, error) {
	shareBasicIdKey := fmt.Sprintf("%s%v", cacheShareBasicIdPrefix, id)
	var resp ShareBasic
	err := m.QueryRowCtx(ctx, &resp, shareBasicIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shareBasicRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShareBasicModel) Insert(ctx context.Context, data *ShareBasic) (sql.Result, error) {
	shareBasicIdKey := fmt.Sprintf("%s%v", cacheShareBasicIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, shareBasicRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Identity, data.UserIdentity, data.RepositoryIdentity, data.UserRepositoryIdentity, data.ExpiredTime, data.ClickNum, data.DeletedAt)
	}, shareBasicIdKey)
	return ret, err
}

func (m *defaultShareBasicModel) Update(ctx context.Context, data *ShareBasic) error {
	shareBasicIdKey := fmt.Sprintf("%s%v", cacheShareBasicIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shareBasicRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Identity, data.UserIdentity, data.RepositoryIdentity, data.UserRepositoryIdentity, data.ExpiredTime, data.ClickNum, data.DeletedAt, data.Id)
	}, shareBasicIdKey)
	return err
}

func (m *defaultShareBasicModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheShareBasicIdPrefix, primary)
}

func (m *defaultShareBasicModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shareBasicRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultShareBasicModel) tableName() string {
	return m.table
}
