// Code generated by goctl. DO NOT EDIT.
package types

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	RepositoryId int64  `json:"repositoryId"`
	Name         string `json:"name"`
	Ext          string `json:"ext"`
	Size         int64  `json:"size"`
	Path         string `json:"path"`
}

type ShareBasicCreateRequest struct {
	UserRepositoryId int64 `json:"userRepositoryId"`
	ExpiredTime      int64 `json:"expiredTime"`
}

type ShareBasicCreateResponse struct {
	Id int64 `json:"id"`
}

type ShareBasicSaveRequest struct {
	RepositoryId int64 `json:"repositoryId"` //分享的文件id
	ParentId     int64 `json:"parentId"`     //保存在该parentId目录下
}

type ShareBasicSaveResponse struct {
	Id int64 `json:"id"`
}
