// Code generated by goctl. DO NOT EDIT.
// Source: repository.proto

package server

import (
	"context"

	"butane-netdisk/service/repository/rpc/internal/logic"
	"butane-netdisk/service/repository/rpc/internal/svc"
	"butane-netdisk/service/repository/rpc/types/repository"
)

type RepositoryServer struct {
	svcCtx *svc.ServiceContext
	repository.UnimplementedRepositoryServer
}

func NewRepositoryServer(svcCtx *svc.ServiceContext) *RepositoryServer {
	return &RepositoryServer{
		svcCtx: svcCtx,
	}
}

func (s *RepositoryServer) GetRepositoryPoolByRepositoryId(ctx context.Context, in *repository.RepositoryReq) (*repository.RepositoryResp, error) {
	l := logic.NewGetRepositoryPoolByRepositoryIdLogic(ctx, s.svcCtx)
	return l.GetRepositoryPoolByRepositoryId(in)
}

func (s *RepositoryServer) DeleteById(ctx context.Context, in *repository.DeleteByIdReq) (*repository.DeleteByIdResp, error) {
	l := logic.NewDeleteByIdLogic(ctx, s.svcCtx)
	return l.DeleteById(in)
}
