// Code generated by goctl. DO NOT EDIT.
package types

type FileUploadRequest struct {
}

type FileUploadResponse struct {
	Id int64 `json:"id"`
}

type FileUploadByChunkRequest struct {
}

type FileUploadByChunkResponse struct {
	Id int64 `json:"id"`
}
